config/routes.rb
Vote::Application.routes.draw do

  get 'main/index'

  resources :payments, :only => [ :create, :new ]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users,
             :skip => [ :sessions, :registrations, :passwords ]
  devise_for :participant, :organization,
             :path_names => {
                 :sign_in => 'login',
                 :sign_up => 'regup',
                 :sign_out => 'logout'
             },
             :controllers => { :sessions => :login, registrations: 'ajax_registrations', passwords: 'ajax_passwords' }

  resource :participant, :except => [ :create, :update ] do
    post 'invite' => 'participants#create_invite'
    resources :claims, :only => [:index]
    resources :phones, :only => [:create, :destroy]
    resources :unconfirmed_phones, :only => [:create, :update]
    get 'votings' => 'participants#show_active_votings'
    get 'closed_votings' => 'participants#show_closed_votings'
    post 'recover_password' => 'participants#recover_password', as: 'recover_pass'
    get 'invite/via/:social' => 'participants#invite_via_social', constraints: { social: /(?:vk|fb|tw|gp|ok)/ }, as: 'invite_via'
  end

  resource :organization, :except => [ :create, :update ] do
    get 'form' => 'organizations#edit', :as => 'edit_form_for'
    delete 'document/:id/destroy' => 'organizations#drop_document', :as => 'destroy_document_of'
    delete 'voting/:id/destroy' => 'organizations#drop_voting', :as => 'destroy_voting_of'
  end

  root to: 'main#index'
  get '/org' => 'main#org', as: 'main_org'

  resources :other_actions, only: [ ] do
    post 'do/by/:email(/:phone(/:firstname(/:secondname(/:fathersname))))' => 'other_actions#do', as: 'do_it'
  end

  resources :text_page, path: :pages, controller: :main, only: [ :show ]

  ActiveAdmin.routes(self)

  resources :other_votings, only: [:show], path: '/smm_voting' do
    resources :social_posts, only: [:create]
  end

  resources :votings, :monetary_votings, :other_votings, path: :votings, controller: :votings do
    post 'info/:number/at/:position' => 'votings#info_about_number', :as => :number_info_at_position_for
    put 'spend_votes' => 'votings#update_votes_matrix'
    get 'get_timer', as: :timer
    resources :claims, :only => [:create] do
      collection do
        post 'with/:phone' => 'claims#create', constraints: { phone: /\d{10}/ }
      end
    end
    member do
      get 'widget'
      get 'frame'
    end
  end

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

  match 'auth/:action/callback' => 'omniauth', as: :omniauth
  match 'oauthorize' => 'omniauth#finish_oauthorize'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :key, :value
  self.primary_key = :key
  validates :key, presence: true, uniqueness: true

  def self.[]( key )
    find key
  end
end

app/views/_settings/_organization.html.haml
.row.settings
  .col.two_thirds
    = form_for who,
      url: organization_path, method: 'put',
      html: { class: 'form', enctype: 'multipart/form-data', multitype: true, data: { type: 'json', edited: t('organization.edit.edited') } },
      remote: true do |f|
      %h1= t 'organization.edit.title'
      %p= t 'organization.edit.explanation'

      %h3= t 'organization.edit.face.contact'
      .row
        .col= inp f, :secondname, between: '*'
        .col
          = f.label :phone, for: 'phone_mask0'
          *
          %input{ id: 'phone_mask0', type: 'text', value: who.phone }
          = f.hidden_field :phone
          :javascript
            ajok_mask(
              $('#phone_mask0'),
              '+7(999)999-99-99',
              (/^\+7\((\d{3})\)(\d{3})-(\d{2})-(\d{2})$/),
              '+7(___)___-__-__'
            );
      .row
        .col= inp f, :firstname, between: '*'
        .col= inp f, :fathersname

      %h3= t 'organization.edit.face.company'
      .row
        .col= inp f, :org_name, between: '*'
        .col= inp f, :site
      .row
        .col= inp f, :jur_address, between: '*'
        .col= inp f, :post_address, between: '*'
      .row
        .col= inp f, :rc, between: '*'
        .col= inp f, :kc, between: '*'
      .row
        .col= inp f, :bik, between: '*'
        .col= inp f, :kpp, between: '*'
      .row
        .col= inp f, :inn, between: '*'
        .col= inp f, :ceo, between: '*'

      .row#settings_organization_documents
        %p= t 'activerecord.attributes.organization.documents'
        #settings_organization_documents_wrapper
          - current_organization.documents.actual.each do |d|
            .document_handler.lightgreenoblue{ :data => { :id => d.id } }
              %a.attachment_link{ href: d.attachment }= d.attachment_file_name
              .fa.del &#xf00d;

        .button#settings_organization_documents_button
          = t 'organization.edit.documents.load'
          = f.file_field :documents, :name => 'organization[documents][]'
      .row.row_with_button
        .col.small_notation= t 'organization.edit.important'
        = f.submit t('organization.edit.send.data'), class: 'col'

      .row
        .button#settings_organization_logo_button
          = f.file_field :avatar
          = t 'organization.edit.logo.load'


  .col.one_third{ style: "padding-top: 80px;" }
    .settings_box
      = form_for who, as: 'who_change_email', url: '/organization', method: 'put', html: { name: 'email_organization_change', class: 'form' }, remote: true do |fe|
        %h1= t 'organization.edit.email.title'
        .row= inp fe, :email, between: '*'
        .row= inp fe, :current_password, type: :password_field, between: '*'
        .row.row_with_button= fe.submit t('organization.edit.email.save')

    .settings_box#password_settings
      = form_for who, as: 'who_change_password', 
        url: '/organization', method: 'put', 
        html: { name: 'password_organization_change', class: 'form', 
          data: { edited: t('organization.edit.password.edited'), empty: t('organization.edit.password.empty') } }, 
        remote: true do |fp|
        %h1= t 'organization.edit.password.title'
        .row= inp fp, :current_password, :type => :password_field, between: '*'
        .row= inp fp, :password, :type => :password_field, between: '*'
        .row= inp fp, :password_confirmation, :type => :password_field, between: '*'
        .row.row_with_button= fp.submit t('organization.edit.password.save')

    :javascript
      (function(){
        $('#password_settings').on('ajax:beforeSend', function(e, xhr){
          var b = true;
          $(this).find('input[type="password"]').each(function(){
            if( !$(this).val().length ){
              $(e.target).trigger( 'custom:alert', [ $(e.target).data('empty'), undefined ] );
              b = false;
              return false;
            }
          });
          return b;
        });

        $('#password_settings').on('ajax:success', function(e, data){
          if( !data._success ) return;
          $(this).find('input[type="password"]').val('');
        });
      })();

app/views/_settings/_participant.html.haml
.row.settings
  .col.two_thirds
    = form_for who,
      url: participant_path, method: 'put',
      html: { class: 'form', data: { type: 'json', edited: t('participant.settings.edited') }, multipart: true },
      remote: true do |f|
      %h1= t 'participant.settings.main.header'
      %p= t 'participant.settings.main.description'

      %h3= t 'participant.settings.main.personal_info'
      .row
        .col= inp f, :secondname, :between => '*'
        .col
          %h4
            = f.label :age
            *
          .select#settings_participant_age_select
            = f.text_field :age, class: 'select_current select_input', readonly: true, data: { listok: 'false' }
            .select_list
              - (5..99).each do |i|
                %div{ data: { select: i } }= i
      .row
        .col= inp f, :firstname, :between => '*'
        .col
          %h4
            = f.label :gender
            *
          .row{ style: 'line-height: 31px;' }
            = f.radio_button :gender, true
            = f.label :gender, t('participant.settings.main.gender.male'), value: true
            = f.radio_button :gender, false
            = f.label :gender, t('participant.settings.main.gender.female'), value: false, style: 'margin-left: 30px;'
      .row.row_with_button
        .col
          .button{ data: { delete: t('participant.settings.avatar.delete') } }
            = t 'participant.settings.avatar.load'
            = f.file_field :avatar, :accept => 'image/*'

      %h3= t 'participant.settings.main.contact_info'
      .row
        .col= inp f, :email, :between => '*'
        .col= inp f, :city, :between => '*'
      .row.row_with_button
        .col.small_notation
          %span *
          = t 'organization.logup.field_required'
        .col= f.submit t('participant.settings.main.update')


    -#%h1= t 'participant.settings.table.title'
    -#%table#settings_participant_history_table
    -#  %tr.row_with_names
    -#    %td.date= t 'participant.settings.table.date'
    -#    %td.amount= t 'participant.settings.table.amount'
    -#    %td.status= t 'participant.settings.table.status'
    -#    %td.method= t 'participant.settings.table.method'
    -#  - who.payments.each do |payment|
    -#    %tr
    -#      %td.date= l payment.created_at.to_date, format: :short
    -#      %td.amount= payment.amount
    -#      %td.status= payment.is_approved
    -#      %td.method= payment.human_currency


  -#.col.one_third
  -#  .settings_box#send_invitation_settings
  -#    = form_tag invite_participant_path(current_participant), method: 'post',
  -#      remote: true, format: :json,
  -#      class: 'form', data: { sended: t('participant.settings.invite.sended'), not_sended: t('participant.settings.invite.not_sended') } do
  -#      = decide_how_invite
  -#      %h1= t 'participant.settings.invite.title'
  -#      %p= t 'participant.settings.invite.description'
  -#
  -#      .row= text_field_tag :email
  -#      .row.row_with_button= submit_tag t('participant.settings.invite.send')
  -#      .row
  -#        .button.social_button.social_button_vk
  -#        .button.social_button.social_button_f
  -#        .button.social_button.social_button_t
  -#        .button.social_button.social_button_g
  -#        .button.social_button.social_button_od
  -#
  -#
  -#  .settings_box#phones_settings
  -#    %h1= t 'participant.settings.phone.all'
  -#    #settings_user_phones{ style: "margin-bottom: #{current_participant.phones.empty? ? 0 : 20}px" }
  -#      #current_phones_for_js
  -#        - if current_participant.phones.empty?
  -#          = form_for UnconfirmedPhone.new,
  -#            url: participant_unconfirmed_phone_path( current_participant ), method: 'put',
  -#            remote: true, format: :json,
  -#            html: { class: 'form', id: 'phone_confirm_after',
  -#              data: { unconfirmed: t('participant.settings.phone_popup.middle.error.unconfirmed'),
  -#                      code: t('participant.settings.phone_popup.middle.error.code'),
  -#                      phone: t('participant.settings.phone_popup.middle.error.phone') } } do |f|
  -#            .row.phone_confirm_description= raw( t('participant.settings.phone_popup.middle.description') )
  -#
  -#            .row
  -#              %input{ name: 'number', type: 'hidden', id: 'hidden_number_after', value: current_participant.unconfirmed_phones.first.number }
  -#              %input{ name: 'confirmation_code', type: 'text' }
  -#
  -#            .row
  -#              = f.submit t 'participant.settings.phone_popup.middle.check'
  -#        - else
  -#          - current_participant.phones.each do |phone|
  -#            = form_for phone,
  -#              url: participant_phone_path( phone ), method: 'delete',
  -#              remote: true, format: :json,
  -#              html: { class: 'settings_uset_phone', data: { cannot: t('participant.settings.phone.cannot') } } do |f|
  -#              = phone.number
  -#              = f.submit raw('&#10006;'), class: 'delete_phone', data: { ask: t('participant.settings.phone.sure') }
  -#
  -#    - unless current_participant.phones.empty?
  -#      = form_for UnconfirmedPhone.new,
  -#        url: participant_unconfirmed_phones_path( current_participant ), method: 'post',
  -#        remote: true, format: :json,
  -#        html: { class: 'form', id: 'participant_settings_add_phone',
  -#          data: { added: t('participant.settings.phone.added'), error: t('participant.settings.phone.error'), unconfirmed: t('participant.settings.phone.unconfirmed') } } do |f|
  -#
  -#        %h1= t 'participant.settings.phone.add'
  -#        .row
  -#          %label{ for: 'phone32' }= t 'activerecord.attributes.organization.phone'
  -#          %input{ id: 'phone32', type: 'text' }
  -#          = f.hidden_field :number
  -#        .row.row_with_button= submit_tag t('participant.settings.phone.save')

      :javascript
        ajok_mask(
          $("#phones_settings #phone32"),
          '+7(999)999-99-99',
          (/^\+7\((\d{3})\)(\d{3})-(\d{2})-(\d{2})$/),
          '+7(___)___-__-__'
        );

        (function(){
          $('#current_phones_for_js').on('ajax:success', function(e, data){
            if( !data._success ) return;

            $(e.target).remove();
          });
        })();

    .settings_box#password_settings
      = form_for who,
        url: participant_path, method: 'put',
        html: { class: 'form',
          data: { empty: t('participant.settings.password_change.empty'), edited: t('participant.settings.password_change.edited') } },
        remote: true do |fu|
        %h1= t 'participant.settings.password_change.change'
        .row= inp fu, :current_password, :type => :password_field
        .row= inp fu, :password, :type => :password_field
        .row= inp fu, :password_confirmation, :type => :password_field
        .row.row_with_button= fu.submit t('participant.settings.password_change.save')

    :javascript
      (function(){
        $('#password_settings').on('ajax:beforeSend', function(e, xhr){
          var b = true;
          $(this).find('input[type="password"]').each(function(){
            if( !$(this).val().length ){
              $(e.target).trigger( 'custom:alert', [ $(e.target).data('empty'), undefined ] );
              b = false;
              return false;
            }
          });
          return b;
        });

        $('#password_settings').on('ajax:success', function(e, data){
          if( !data._success ) return;
          $(this).find('input[type="password"]').val('');
        });
      })();

- content_for :layout_bottom do

  #layer_3_smoke
  #layer_3_body
    .app_div
      = form_for UnconfirmedPhone.new,
        url: participant_unconfirmed_phone_path( current_participant ), method: 'put',
        remote: true, format: :json,
        html: { class: 'form phone_confirm_popup', id: 'phone_confirm',
          data: { unconfirmed: t('participant.settings.phone_popup.middle.error.unconfirmed'),
                  code: t('participant.settings.phone_popup.middle.error.code'),
                  phone: t('participant.settings.phone_popup.middle.error.phone') } } do |f|
        .cross &#10006;
        .row.phone_confirm_description= raw( t('participant.settings.phone_popup.middle.description') )

        .row
          %input{ name: 'number', type: 'hidden', id: 'hidden_number' }
          %input{ name: 'confirmation_code', type: 'text' }

        .row
          = f.submit t 'participant.settings.phone_popup.middle.check'

      = content_for :layout_bottom_claim

  :javascript
    (function(){
      var smoke = $('#layer_3_smoke');
      var body = $('#layer_3_body');
      var layer = body.add(smoke);

      var forms = body.find('form');

      body.find('.cross').on('mousedown', function(){ layer.fadeOut(500); });


      var start_form = $('#participant_settings_add_phone');

      start_form.on('ajax:success', function(e, data){
        if( !data._success ) return;

        middle_form.find('#hidden_number').val( data.number );
        middle_form.data('with_claim', false);

        layer.fadeIn(500);
        forms.eq(0).show();
        forms.eq(1).hide();
        $("body").animate({ scrollTop: 0 }, 300);
      });


      var middle_form = $('#phone_confirm');
      var finish_form = $('#phone_add_to_voting');

      middle_form.on('ajax:success', function(e, data) {
        if(!data._success) return;

        if(!middle_form.data('with_claim')) {
          layer.fadeOut(500);
          if (start_form.data('added') != null)
            middle_form.trigger( 'custom:alert', [ start_form.data('added'), '' ] );
          return;
        } else {
          finish_form.find('#hidden_phone').val( data.phone );

          layer.fadeIn(500);
          forms.eq(1).show();
          forms.eq(0).hide();
          $("body").animate({ scrollTop: 0 }, 300);
        }
      });

      finish_form.on('ajax:success', function(e, data) {
        if( data._success ) layer.fadeOut(500);
      });

      #{"middle_form.find('#hidden_number').val(#{current_participant.unconfirmed_phones.first.number});

        layer.fadeIn(500);
        forms.eq(0).show();
        $('body').animate({ scrollTop: 0 }, 300);" if current_participant.phones.empty?}
    })();