config/routes.rb
Vote::Application.routes.draw do

  get 'main/index'

  resources :payments, :only => [ :create, :new ]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users,
             :skip => [ :sessions, :registrations, :passwords ]
  devise_for :participant, :organization,
             :path_names => {
                 :sign_in => 'login',
                 :sign_up => 'regup',
                 :sign_out => 'logout'
             },
             :controllers => { :sessions => :login, registrations: 'ajax_registrations', passwords: 'ajax_passwords' }

  resource :participant, :except => [ :create, :update ] do
    post 'invite' => 'participants#create_invite'
    resources :claims, :only => [:index]
    resources :phones, :only => [:create, :destroy]
    resources :unconfirmed_phones, :only => [:create, :update]
    get 'votings' => 'participants#show_active_votings'
    get 'closed_votings' => 'participants#show_closed_votings'
    post 'recover_password' => 'participants#recover_password', as: 'recover_pass'
    get 'invite/via/:social' => 'participants#invite_via_social', constraints: { social: /(?:vk|fb|tw|gp|ok)/ }, as: 'invite_via'
  end

  resource :organization, :except => [ :create, :update ] do
    get 'form' => 'organizations#edit', :as => 'edit_form_for'
    delete 'document/:id/destroy' => 'organizations#drop_document', :as => 'destroy_document_of'
    delete 'voting/:id/destroy' => 'organizations#drop_voting', :as => 'destroy_voting_of'
  end

  root to: 'main#index'
  get '/org' => 'main#org', as: 'main_org'

  resources :other_actions, only: [ ] do
    post 'do/by/:email(/:phone(/:firstname(/:secondname(/:fathersname))))' => 'other_actions#do', as: 'do_it'
  end

  resources :text_page, path: :pages, controller: :main, only: [ :show ]

  ActiveAdmin.routes(self)

  resources :other_votings, only: [:show], path: '/smm_voting' do
    resources :social_posts, only: [:create]
  end

  resources :votings, :monetary_votings, :other_votings, path: :votings, controller: :votings do
    post 'info/:number/at/:position' => 'votings#info_about_number', :as => :number_info_at_position_for
    put 'spend_votes' => 'votings#update_votes_matrix'
    get 'get_timer', as: :timer
    resources :claims, :only => [:create] do
      collection do
        post 'with/:phone' => 'claims#create', constraints: { phone: /\d{10}/ }
      end
    end
    member do
      get 'widget'
      get 'frame'
    end
  end

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

  match 'auth/:action/callback' => 'omniauth', as: :omniauth
  match 'oauthorize' => 'omniauth#finish_oauthorize'

end

app/models/voting.rb
#encoding: utf-8
class Voting < ActiveRecord::Base

  WAYS = %w(count_users sum date count_points)

  STATUSES = { 0 => :pending, 1 => :active, 2 => :prizes, 3 => :close }

  attr_accessible :name, :start_date, :way_to_complete, :min_count_users,
                  :end_date, :prize, :brand, :prize1, :prize2, :prize3, :status, :description,
                  :custom_head_color, :custom_background, :custom_background_color

  prize_options = { styles: { original: '400x400>', full: "220x265>", thumb: "100x100>" },
                    default_url: 'http://placehold.it/1x1/ffffff/ffffff',
                    path: ':rails_root/public/system/images/prize/:style/:filename',
                    url: '/system/images/prize/:style/:filename' }

  has_attached_file :prize, prize_options
  has_attached_file :prize1, prize_options
  has_attached_file :prize2, prize_options
  has_attached_file :prize3, prize_options

  has_attached_file :brand,
                    :styles => { :original => "200x70>", :thumb => "50x50>" },
                    :default_url => 'http://placehold.it/1x1/ffffff/ffffff',
                    :path => ':rails_root/public/system/images/brand/:style/:filename',
                    :url => '/system/images/brand/:style/:filename'

  has_attached_file :custom_background,
                    :path => ':rails_root/public/system/images/custom_background/:filename',
                    :url => '/system/images/custom_background/:filename'

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :organization
  has_one :strategy

  scope :active, -> { where status: 1, end_timer: nil }
  scope :closed, -> { where status: 2..3 }

  validates :name, :description, :start_date, :presence => true
  validates :way_to_complete, inclusion: { in: WAYS }
  validates :custom_head_color, :custom_background_color, format: { with: /\A#[0-9a-f]{6}\z/i }, allow_blank: true
  validates :status, exclusion: { in: [:active],
                                  message: :first_confirm_org }, unless: 'organization.is_confirmed?'

  validate :not_past_date, if: 'id.nil?'
  validate :start_before_end

  after_create :set_default_status
  before_save :images_names

  def active?; status == :active end

  def status
    STATUSES[read_attribute(:status)]
  end

  def status= (s)
    if s.is_a? Integer
      write_attribute :status, s
    elsif (!!(s =~ /^[-+]?[0-9]+$/)) && ((0..3).find s.to_s.to_i)
      write_attribute :status, s.to_s.to_i
    elsif !STATUSES.key(s.to_sym).nil?
      write_attribute :status, STATUSES.key(s.to_sym)
    end
  end

  def can_vote_for_claim?
    status == :active && start_date < DateTime.now
  end

  def can_register_in_voting?
    status == :active
  end

  def complete!
    update_attributes! status: 2, end_date: Date.today
  end

  def complete_if_necessary!
    if need_complete?
      complete!
      return true
    end
    return false
  end


  protected

  def retrive_position_and_length_to_first (phone_number)
    lengths = []

    phone.each_with_index do |p, i|
      l = p.length_to_first_place_for_number phone_number[i]
      lengths.push({ i: i, l: l }) if (block_given? ? yield(l) : true)
    end
    lengths
  end

  def set_default_status
    self.status ||= '0'
  end

  def not_past_date
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "не может быть в прошлом")
    end
  end

  def start_before_end
    if end_date.present? && end_date < start_date
      errors.add(:end_date, "не может быть раньше чем дата начала")
    end
  end

  def images_names
    %w( prize prize1 prize2 prize3 brand custom_background ).each do |image|
      next unless send "#{image}_file_name_changed?"
      extension = send("#{image}_content_type").gsub 'image/', '.'
      send(image).instance_write :file_name, "#{SecureRandom.uuid}.#{extension}"
    end
  end
end

app/controllers/voting_controller.rb
class VotingController < ApplicationController
  before_filter :authenticate_user!, :except => [ :widget ]

  def join
    render :json => { :status => 'OK' }
  end

  def show
    @who = current_user
    @what = current_user.claims.first
  end

  def widget
  end

  def info_about_number
    @who = current_user
    @what = Claim.where(:voting_id => params[:id], :participant_id => current_user.id).first
    @which = params[:number].to_i
    @on = params[:position].to_i
    @rate = @what.voting.phone[@on].get_rating_for_number @which
    render :partial => 'voting/number_info'
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  before_filter :authenticate_participant!, :only => [ :info_about_number, :join, :update_votes_matrix]
  before_filter :authenticate_organization!, :only => [ :new, :create, :edit, :update, :destroy, :frame]
  before_filter :can_vote_for_claim?, :only => [ :update_votes_matrix ]
  #load_and_authorize_resource

  before_filter :check_date_hours, only: [ :create, :update ]



  def frame
    @voting = Voting.find_by_slug params[:id]
    render layout: 'organizations'
  end

  def new
    @voting = ( params[:type] == 'monetary' ? MonetaryVoting : OtherVoting ).new
    render 'votings/new/index', layout: 'organizations'
  end

  def edit
    @voting = Voting.find_by_slug params[:id]
    render 'votings/new/index', layout: 'organizations'
  end

  def update
    @voting = Voting.find_by_slug params[:id]

    return render json: { _success: false, _alert: 'cannot' } unless can? :update, @voting

    if @voting.update_attributes params[:voting]
      render json: { _success: true, _path_to_go: organization_path }
    else
      render json: { _success: false, _resource: 'voting', _errors: @voting.errors.messages }
    end
  end

  def index
    @number = params[:number]

    @votings = MonetaryVoting.active.all
    unless @number.nil?
      phone = Phone.new number: @number
      @votings.sort_by! do |voting|
        voting[:max_coincidence] = voting.matches_count phone
        -voting[:max_coincidence]
      end
    end
    @votings += OtherVoting.active.all

    if request.xhr?
      render layout: false
    else
      render 'main/index'
    end
  end

  def create
    # TODO: do things right?
    type = params[:voting].delete :type
    if type == 'monetary_voting'
      voting = MonetaryVoting.new params[:voting]
    else
      voting = OtherVoting.new params[:voting]
    end
    voting.organization = current_organization
    voting.save!

    render json: { _success: true, _alert: 'created', _path_to_go: organization_path }
  rescue
    render json: { _success: false, _resource: 'voting', _errors: voting.errors.messages}
  end

  def show
    @voting = MonetaryVoting.find params[:id]
    @lead_phone_number = @voting.phone.lead_phone_number
    phones = participant_signed_in? ? current_participant.phones : []
    votes_matrix = @voting.phone
    @sorted_phones_with_checks = Array.new( 11 ){ Array.new };
    @phones_not_in_voting = Array.new( 11 ){ Array.new };
    phones.each do |phone|
      phone_with_checks = Array.new( 10 )
      count = 0
      phone_in_voting = phone.claims.where(:voting_id => @voting.id).present?
      string = ''
      phone.each_with_index do |number, i|
        position = votes_matrix.positions[i]
        place = position.place_for_number number
        count += 1 if place == 1
        points_to_first = phone_in_voting && place != 1 ? position.length_to_first_place_for_number( number ) : -1
        string += number.to_s
        phone_with_checks[i] = [ number, place, points_to_first ]
      end
      if phone_in_voting
        @sorted_phones_with_checks[count].push( { id: phone.id, numbers: phone_with_checks, place: @voting.determine_place(phone) } )
      else
        @phones_not_in_voting[count].push( { id: phone.id, numbers: phone_with_checks, string: string } )
      end
    end

    if @voting.can_vote_for_claim? || @voting.can_register_for_voting?
      render 'votings/show/active', layout: participant_signed_in? ? 'participants' : 'voting_any_who'
    else
      if @voting.is_a? MonetaryVoting
        lead_claim = @voting.lead_claim
        @stats = [ ClaimStatistic.where(claim_id: lead_claim.id).sort_by(&:created_at) ]
        if participant_signed_in?
          your_lead_claim = Claim.where(participant_id: current_participant.id,
                                        voting_id: @voting.id).sort_by { |c| @voting.determine_place(c.phone) }.last
          @stats << ClaimStatistic.where(claim_id: your_lead_claim.id).sort_by(&:created_at) unless your_lead_claim.nil?
        end
      end
      render 'votings/show/closed', layout: participant_signed_in? ? 'participants' : 'voting_any_who'
    end
  end

  def update_votes_matrix
    points = (params[:points]).to_i

    claim = Claim.where(participant_id: current_participant.id,
                        voting_id: params[:voting_id],
                        phone_id: params[:phone_id]).first

    monetary_voting = MonetaryVoting.find params[:voting_id]
    monetary_voting.vote_for_claim(claim, points)

    vt = VoteTransaction.new amount: points
    vt.claim = claim
    vt.participant = current_participant
    vt.save!

    render json: { _success: true, _path_to_go: '' }
  rescue Exceptions::PaymentRequiredError
    render json: { _success: false, _alert: 'cost' }
  end

  def widget
    @voting = MonetaryVoting.find params[:id]
    @phone = current_participant.phone unless current_participant.nil?
    respond_to do |format|
      format.html {render layout: false}
      format.json {render json: @voting}
    end
  end

  def info_about_number
    @what = Claim.where(voting_id: params[:voting_id], participant_id: current_participant.id).first
    @which = params[:number].to_i
    @on = params[:position].to_i
    @rate = @what.voting.phone[@on].get_rating_for_number @which
    @spend_votes = @what.voting.phone[@on].length_to_next_rate_for_number @which
    render partial: 'number_info'
  end

  def destroy
    @voting = Voting.find_by_slug params[:id]
    return render json: { notice: I18n.t('voting.status.cannot_delete_active_voting') } unless can? :destroy, @voting
    @voting.destroy
    respond_to do |format|
      format.html { redirect_to :back, method: :get, status: 200 }
      format.json { render :ok }
    end
  end

  protected

  def can_vote_for_claim?
    voting = MonetaryVoting.find params[:voting_id]
    render json: { _success: false, _alert: 'close' } unless voting.can_vote_for_claim?
  end

  def check_date_hours
    params[:voting][:start_date] = add_hour_to_date params[:voting][:start_date], params[:start_date_hour]
    params[:voting][:end_date] = add_hour_to_date params[:voting][:end_date], params[:end_date_hour]
  end

  def add_hour_to_date( date, hour )
    if !(date.blank? || hour.blank?)
      date = Date.parse date
      date += hour.to_i.hours
    end

    date
  end

end

app/helpers/votings_helper.rb
#encoding: utf-8
module VotingsHelper
  def frame_for(voting)
    url = voting.is_a?(MonetaryVoting) ? voting_url(voting) : other_voting_url(voting)
"<iframe src='#{url}'  width=100% height=1024 scrolling=no frameborder=0>
<p>
Ваш браузер не поддерживает вставки страниц. Перейдите <a href=src='#{url}>по прямой ссылке</a>
</p>
</iframe>"
  end

  def voting_image_url( image, holder = nil )
    if image.path
      image.url
    elsif holder
      "http://placehold.it/#{holder}"
    end
  end

  def voting_image( image, holder = nil )
    url = voting_image_url image, holder

    if url
      "background-image: url('#{url}');"
    else
      nil
    end
  end
end

app/views/votings/_widget.slim
- if voting.is_a? MonetaryVoting
  =render partial: 'monetary_votings/widget', locals: {voting: voting}
- else
  =render partial: 'other_votings/widget', locals: {voting: voting}

app/views/votings/frame.html.haml
.voting_new
  %h1
    Код для вставки на сайт
  .frame
    %code
      =frame_for @voting

app/views/votings/index.html.haml
- @big_votings = @votings.to(1)
- @small_votings_groups = ( @votings.from(2) ).each_slice(4)

.widget_row.double_widget
  =render :partial => "votings/widget", :collection => @big_votings, :as => 'voting'

- @small_votings_groups.each do |small_votings|
  .widget_row
    =render :partial => "votings/widget", :collection => small_votings, :as => 'voting'

app/views/votings/index.slim
- @big_votings = @votings.to(1)
- @small_votings_groups = ( @votings.from(2) ).each_slice(4)

.widget_row.double_widget
  = render partial: "votings/widget", collection: @big_votings, as: 'voting'

- @small_votings_groups.each do |small_votings|
  .widget_row
    = render partial: "votings/widget", collection: small_votings, as: 'voting'

coffee:
  $('[data-time]').each ()->
    new Timer $ this
    return

app/views/votings/new_another.html.haml
#body.create_voting
  .first.half
    = form_for @voting, :url => votings_path, :html => { :name => 'create_monetary_poll' } do |f|
      = f.hidden_field :type, :value => :another_voting
      
      = render "votings/new_partial/common_part", :f => f

      %h3.tgreenoblue
        = t 'organization.poll.finance.parameters'
      .row
        .elem.first.half
          = f.label :points_limit, :class => 'tgrey'
          = f.text_field :points_limit
        .elem.second.half
          = f.label :cost_10_points, :class => 'tgrey'
          = f.text_field :cost_10_points

      %h3.tgreenoblue
        = t 'organization.poll.actions.title'
      .row
        = render 'votings/new_partial/actions_form', :f => f


      .row.last
        .button.yellow
          = link_to t('organization.poll.save_and_check'), 'javascript:document.forms["create_monetary_poll"].submit()', :class => 'tblack'

  = render "votings/new_partial/second_half"

app/views/votings/new_monetary.html.haml
#body.create_voting
  .first.half
    = form_for @voting, as: 'voting',
      url: votings_path,
      html: { class: 'default_form', name: 'create_monetary_poll', multipart: true },
      remote: true do |f|
      = f.hidden_field :type, :value => :monetary_voting

      = render "votings/new_partial/common_part", :f => f, :active => 'first'

      %h3.tgreenoblue
        = t 'organization.poll.h3.finance'
      .row
        .elem.first.half
          = f.label :cost, :class => 'tgrey'
          = f.text_field :cost
        .elem.second.half
          = f.label :timer, :class => 'tgrey'
          = f.text_field :timer
      .row
        .elem.first.half
          = f.label :financial_threshold, :class => 'tgrey'
          = f.text_field :financial_threshold
        .elem.second.half
          = f.label :min_sum, :class => 'tgrey'
          = f.text_field :min_sum

      %h3.tgreenoblue
        = t 'organization.poll.h3.fixed'
      .row
        .elem.wide
          = label :voting_fake, :cost, t('organization.poll.calculation.cost'), :class => 'tgrey'
          = text_field :voting_fake, :cost, :class => 'ranged', :data => { :currency => t('organization.poll.currency.cost'), :fix => t('organization.poll.fixed.variant.cost'), :type => 'cost', :target => 'voting_cost', :min => 0, :max => 500, :step => 10 }
      .row
        .elem.wide
          = label :voting_fake, :users_population, t('organization.poll.calculation.users_population'), :class => 'tgrey'
          = text_field :voting_fake, :users_population, :class => 'ranged', :data => { :currency => t('organization.poll.currency.users_population'), :fix => t('organization.poll.fixed.variant.users_population'), :type => 'users_population', :min => 0, :max => 10000, :step => 100 }
      .row
        .elem.wide
          = label :voting_fake, :budget, t('organization.poll.calculation.budget'), :class => 'tgrey'
          = text_field :voting_fake, :budget, :class => 'ranged', :data => { :fix => t('organization.poll.fixed.variant.budget'), :currency => t('organization.poll.currency.budget'), :type => 'budget' , :min => 0, :max => 5000000, :step => 1000 }

      .row.last
        = link_to t('organization.poll.go_back_to_list'), organization_path, class: 'button', style: 'float: left'
        = f.submit t('organization.poll.save_and_check'), class: 'button'

  = render "votings/new_partial/second_half"

app/views/votings/new_other.html.haml
#body.create_voting
  .first.half
    = form_for @voting, as: 'voting', 
    url: votings_path, 
    html: { class: 'default_form', name: 'create_other_poll' } do |f|
      = f.hidden_field :type, :value => :other_voting

      = render "votings/new_partial/common_part", :f => f, :active => 'second'

      %h3.tgreenoblue
        = t 'organization.poll.finance.parameters'
      .row
        .elem.first.half
          = f.label :points_limit, :class => 'tgrey'
          = f.text_field :points_limit
        .elem.second.half
          = f.label :cost_10_points, :class => 'tgrey'
          = f.text_field :cost_10_points

      %h3.tgreenoblue
        = t 'organization.poll.actions.title'
      .normal_row
        = render 'votings/new_partial/actions_form', :f => f

      .row.last
        = link_to t('organization.poll.go_back_to_list'), organization_path, class: 'button', style: 'float: left'
        = f.submit t('organization.poll.save_and_check'), class: 'button'

  = render "votings/new_partial/second_half"

app/views/votings/widget.html.haml
.flash.notice
  = flash[:message]

= stylesheet_link_tag    "application", :media => "all"
= javascript_include_tag "application"
-if voting.is_a? MonetaryVoting
  =render partial: 'votings/widget'
-else
  =render partial: 'other_votings/widget'