config/routes.rb
Vote::Application.routes.draw do

  get 'main/index'

  resources :payments, :only => [ :create, :new ]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users,
             :skip => [ :sessions, :registrations, :passwords ]
  devise_for :participant, :organization,
             :path_names => {
                 :sign_in => 'login',
                 :sign_up => 'regup',
                 :sign_out => 'logout'
             },
             :controllers => { :sessions => :login, registrations: 'ajax_registrations', passwords: 'ajax_passwords' }

  resource :participant, :except => [ :create, :update ] do
    post 'invite' => 'participants#create_invite'
    resources :claims, :only => [:index]
    resources :phones, :only => [:create, :destroy]
    resources :unconfirmed_phones, :only => [:create, :update]
    get 'votings' => 'participants#show_active_votings'
    get 'closed_votings' => 'participants#show_closed_votings'
    post 'recover_password' => 'participants#recover_password', as: 'recover_pass'
    get 'invite/via/:social' => 'participants#invite_via_social', constraints: { social: /(?:vk|fb|tw|gp|ok)/ }, as: 'invite_via'
  end

  resource :organization, :except => [ :create, :update ] do
    get 'form' => 'organizations#edit', :as => 'edit_form_for'
    delete 'document/:id/destroy' => 'organizations#drop_document', :as => 'destroy_document_of'
    delete 'voting/:id/destroy' => 'organizations#drop_voting', :as => 'destroy_voting_of'
  end

  root to: 'main#index'
  get '/org' => 'main#org', as: 'main_org'

  resources :other_actions, only: [ ] do
    post 'do/by/:email(/:phone(/:firstname(/:secondname(/:fathersname))))' => 'other_actions#do', as: 'do_it'
  end

  resources :text_page, path: :pages, controller: :main, only: [ :show ]

  ActiveAdmin.routes(self)

  resources :other_votings, only: [:show], path: '/smm_voting' do
    resources :social_posts, only: [:create]
  end

  resources :votings, :monetary_votings, :other_votings, path: :votings, controller: :votings do
    post 'info/:number/at/:position' => 'votings#info_about_number', :as => :number_info_at_position_for
    put 'spend_votes' => 'votings#update_votes_matrix'
    get 'get_timer', as: :timer
    resources :claims, :only => [:create] do
      collection do
        post 'with/:phone' => 'claims#create', constraints: { phone: /\d{10}/ }
      end
    end
    member do
      get 'widget'
      get 'frame'
    end
  end

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

  match 'auth/:action/callback' => 'omniauth', as: :omniauth
  match 'oauthorize' => 'omniauth#finish_oauthorize'

end

app/models/payment.rb
#encoding: UTF-8

class Payment < ActiveRecord::Base

  CURRENCIES = %w( WMRM BANKOCEAN2R RapidaOceanSvyaznoyR AlfaBankOceanR Qiwi29OceanR VTB24R MegafonR MtsR MobileBeelineR )

  belongs_to :user
  attr_accessible :amount, :user_id, :currency, :with_promo, :promo, :user

  validates :currency, inclusion: { in: CURRENCIES }, presence: true
  validates :promo, if: :with_promo?, presence: true, allow_blank: false

  validate :promo_usable?, if: :with_promo?

  scope :approved, -> { where is_approved: true }
  scope :with_promo, -> { where with_promo: true }

  before_create :default_with_promo

  def approve!
    user.add_funds!(self.amount + promo_bonus + first_paid_bonus)
    user.parent.add_funds!(amount * 0.1) unless (user.parent.nil?) || (user.paid)
    user.paid = 1
    user.save!
    write_attribute :is_approved , 1
    save!
  end

  def amount
    Currency.rur_to_vote read_attribute(:amount)
  end

  def approved?
    read_attribute :is_approved
  end

  def is_approved
    I18n.t "participant.payment.status.#{read_attribute(:is_approved)}"
  end

  def human_currency
    case currency
    when 'WMRM'                 then 'Web Money'
    when 'BANKOCEAN2R'          then 'Bank card'
    when 'RapidaOceanSvyaznoyR' then 'Связной'
    when 'AlfaBankOceanR'       then 'Alfabank'
    when 'Qiwi290OceanR'        then 'Qiwi'
    when 'VTB24R'               then 'ВТБ24'
    end
  end

  def promo_usable?
    promo = Promo.find_by_code self.promo
    !promo.nil? && promo.active? &&
      PromoUses.joins(:promo).where(participant_id: user.id, promos: { code: self.promo }).first.nil?
  end

  def with_promo?
    read_attribute :with_promo
  end

  protected

  def promo_bonus
    promo = Promo.find_by_code self.promo
    if !promo.nil? && promo_usable?
      PromoUses.create! do |pu|
        pu.participant = user
        pu.promo = promo
      end
      promo.amount
    else
      0
    end
  end

  def first_paid_bonus
    if user.paid?
      0
    else
      amount * FirstBonus.value / 100
    end
  end

  def default_with_promo
    with_promo = promo.nil? ? 0 : 1
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_participant!

  def new
    @payment = Payment.new user_id: current_participant
    render partial: 'new'
  end

  def create
    @payment = current_participant.payments.create! params[:payment]
    @promo = Promo.find_by_code @payment.promo
    partial = ''
    with_format(:html) { partial = render_to_string 'payments/_create', layout: false }
    render json: { _success: true,  _content: partial }
  rescue
    render json: { _success: false, _alert: 'error' }
  end
end

app/views/payments/_after_pay.html.haml
= stylesheet_link_tag 'application'

#payment_middleblock
  %p#only{ data: { location: @redirect } }
    = raw "Now you will redirect to <a href='#{@redirect}' target='_parent'>#{@redirect}</a>"

:javascript
  window.top.location.href = document.getElementById('only').dataset.location

app/views/payments/_create.html.haml
= stylesheet_link_tag 'application'

#payment_middleblock
  %h1
    = t 'participant.payment.proceed.title'
  = payment_service_for @payment.id, RobokassaConfig.login,
                          amount: @payment.amount,
                          service: :robokassa,
                          secret: RobokassaConfig.secret_first,
                          currency: @payment.currency,
                          html: { class: 'form' } do |s|
    %p
      = t 'participant.payment.proceed.amount_to_pay', amount: @payment[:amount], points: @payment.amount, count: @payment.amount
    - unless @payment.user.paid?
      %p
        = t 'participant.payment.proceed.amount_of_first_bonus', amount: FirstBonus.value
    - if @payment.with_promo? && @payment.promo_usable?
      %p
        = t 'participant.payment.proceed.amount_of_bonus', amount: @promo.amount, count: @promo.amount
    = submit_tag t 'participant.payment.proceed.to_payment', class: 'button yellow'

app/views/payments/_new.html.haml
%iframe{ name: 'robokassa_frame' }
%div#close_participant_balance_fillup.fa
  &#xf00d;
%div#payment
  %div.head.yellow
    %h1.tblack
      = raw "#{t 'participant.payment.account.on_your'} <b class='tred'>#{current_participant.billinfo} #{t 'participant.payment.account.points', count: current_participant.billinfo}</b>"
  %div.row
    %div.col
      = form_for @payment,
        html: { class: 'form',
          data: { error: t('participant.payment.promo.unusable') } },
        remote: true, format: :json do |f|
        %h1.tblack
          = t 'participant.payment.buy.points'
        %h3.tgreenoblue
          = t 'participant.payment.buy.choose'
        - Payment::CURRENCIES.each_slice(2) do |one, two|
          %div.row
            %div.col.first
              = f.radio_button :currency, one, checked: one == 'WMRM' ? 'checked' : nil
              = f.label "currency_#{one.downcase}", raw("<img src='/images/#{one}.png'>")
            - unless two.nil?
              %div.col
                = f.radio_button :currency, two
                = f.label "currency_#{two.downcase}", raw("<img src='/images/#{two}.png'>")
        %div.row.promo
          %div.col
            = f.check_box :with_promo
            = f.label :with_promo, raw("<p>#{t 'participant.payment.with_promo'}</p>"), class: 'tblack'
          %div.col
            = f.text_field :promo
        %h3.tgreenoblue.last
          = t 'participant.payment.points_for_purchase'
        %div.row
          %div.col.choose_votes
            .choose_votes_changer -
            = text_field :fake, :amount, value: 0, data: { rate: Currency.rate }
            = f.hidden_field :amount, value: 0
            .choose_votes_changer +
          %div.col
            = f.submit 'pay', class: 'button', data: { pay: "#{t('participant.payment.pay')}", amount: 0, currency: "#{t('participant.payment.currency')}" }
    %div.col.greyground
      %h1.tgreenoblue
        = t 'participant.payment.or_take_bonus'
      %p.tblack
        = t 'participant.payment.friends_and_bonus'
      = form_for :some, url: invite_participant_path(current_participant), html: { class: 'form', data: { sended: t('participant.settings.invite.sended') } }, remote: true, format: :json do |f|
        = decide_how_invite
        %div.row
          = f.label :email, t('participant.payment.invite.email'), class: 'tblack'
          = f.text_field :email
        %div.row
          = f.label :phone, t('participant.payment.invite.sms'), class: 'tblack'
          = f.text_field :phone, placeholder: '+7 (___) ___-__-__'
          = f.hidden_field :real_phone
        %div.row
          = f.submit t('participant.payment.invite.send'), class: 'button'
      %div.row.social
        = link_to '', invite_via_participant_path(:vk), class: 'button yellow social_button social_button_vk'
        = link_to '', invite_via_participant_path(:fb), class: 'button yellow social_button social_button_f'
        = link_to '', invite_via_participant_path(:tw), class: 'button yellow social_button social_button_t'
        = link_to '', invite_via_participant_path(:gp), class: 'button yellow social_button social_button_g'
        = link_to '', invite_via_participant_path(:ok), class: 'button yellow social_button social_button_od last'

= javascript_include_tag 'payment'

app/views/payments/new.html.haml
%div#payment
  %div.head.yellow
    %h1
      = raw "#{t 'participant.payment.account.on_your'} <b class='tred'>#{current_participant.billinfo} #{t 'participant.payment.account.points'}</b>"
  %div.row
    %div.col
      = form_for @payment, html: { class: 'form', target: 'robokassa_frame' }, remote: true do |f|
        %h1
          = t 'participant.payment.buy.points'
        %h3.tgreenoblue
          = t 'participant.payment.buy.choose'
        %div.row
          %div.col.first
            = f.radio_button :currency, :WMRM, checked: 'checked'
            = f.label :currency_wmrm, raw("<img src='#{t 'participant.payment.ecurrency.webmoney.path'}'>")
          %div.col
            = f.radio_button :currency, :BANKOCEAN2R
            = f.label :currency_bankocean2r, raw("<img src='#{t 'participant.payment.ecurrency.bankcard.path'}'>")
        %div.row
          %div.col.first
            = f.radio_button :currency, :RapidaOceanSvyaznoyR
            = f.label :currency_rapidaoceansvyaznoyr, raw("<img src='#{t 'participant.payment.ecurrency.svaznoy.path'}'>")
          %div.col
            = f.radio_button :currency, :AlfaBankOceanR
            = f.label :currency_alfabankoceanr, raw("<img src='#{t 'participant.payment.ecurrency.alfa.path'}'>")
        %div.row
          %div.col.first
            = f.radio_button :currency, :Qiwi29OceanR
            = f.label :currency_qiwi29oceanr, raw("<img src='#{t 'participant.payment.ecurrency.qiwi.path'}'>")
          %div.col
            = f.radio_button :currency, :VTB24R
            = f.label :currency_vtb24r, raw("<img src='#{t 'participant.payment.ecurrency.vtb24.path'}'>")
        %div.row.promo
          %div.col
            = f.check_box :with_promo
            = f.label :with_promo, raw("<p>#{t 'participant.payment.with_promo'}</p>")
          %div.col
            = f.text_field :promo
        %h3.tgreenoblue.last
          = t 'participant.payment.points_for_purchase'
        %div.row
          %div.col.choose_votes
            .choose_votes_changer -
            = f.text_field :amount
            .choose_votes_changer +
          %div.col
            = f.submit 'pay', class: 'button', data: { pay: "#{t('participant.payment.pay')}", amount: current_participant.billinfo, currency: "#{t('participant.payment.currency')}" }
    %div.col.greyground
      %h1.tgreenoblue
        = t 'participant.payment.or_take_bonus'
      %p
        = t 'participant.payment.friends_and_bonus'
      = form_for :fake, url: invite_participant_path, html: { class: 'form' }, remote: true do |f|
        %div.row
          = f.label :email, t('participant.payment.invite.email')
          = f.text_field :email
        %div.row
          = f.label :phone, t('participant.payment.invite.sms')
          = f.text_field :phone, placeholder: '+7 (___) ___-__-__', mask: '\d'
        %div.row
          = f.submit t('participant.payment.invite.send'), class: 'button'
      %div.row.social
        = link_to '', invite_via_participant_path(:vk), class: 'button social_button social_button_vk'
        = link_to '', invite_via_participant_path(:fb), class: 'button social_button social_button_f'
        = link_to '', invite_via_participant_path(:tw), class: 'button social_button social_button_t'
        = link_to '', invite_via_participant_path(:gp), class: 'button social_button social_button_g'
        = link_to '', invite_via_participant_path(:ok), class: 'button social_button social_button_od'
= javascript_include_tag 'payment'