config/routes.rb
Vote::Application.routes.draw do

  get 'main/index'

  resources :payments, :only => [ :create, :new ]

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users,
             :skip => [ :sessions, :registrations, :passwords ]
  devise_for :participant, :organization,
             :path_names => {
                 :sign_in => 'login',
                 :sign_up => 'regup',
                 :sign_out => 'logout'
             },
             :controllers => { :sessions => :login, registrations: 'ajax_registrations', passwords: 'ajax_passwords' }

  resource :participant, :except => [ :create, :update ] do
    post 'invite' => 'participants#create_invite'
    resources :claims, :only => [:index]
    resources :phones, :only => [:create, :destroy]
    resources :unconfirmed_phones, :only => [:create, :update]
    get 'votings' => 'participants#show_active_votings'
    get 'closed_votings' => 'participants#show_closed_votings'
    post 'recover_password' => 'participants#recover_password', as: 'recover_pass'
    get 'invite/via/:social' => 'participants#invite_via_social', constraints: { social: /(?:vk|fb|tw|gp|ok)/ }, as: 'invite_via'
  end

  resource :organization, :except => [ :create, :update ] do
    get 'form' => 'organizations#edit', :as => 'edit_form_for'
    delete 'document/:id/destroy' => 'organizations#drop_document', :as => 'destroy_document_of'
    delete 'voting/:id/destroy' => 'organizations#drop_voting', :as => 'destroy_voting_of'
  end

  root to: 'main#index'
  get '/org' => 'main#org', as: 'main_org'

  resources :other_actions, only: [ ] do
    post 'do/by/:email(/:phone(/:firstname(/:secondname(/:fathersname))))' => 'other_actions#do', as: 'do_it'
  end

  resources :text_page, path: :pages, controller: :main, only: [ :show ]

  ActiveAdmin.routes(self)

  resources :other_votings, only: [:show], path: '/smm_voting' do
    resources :social_posts, only: [:create]
  end

  resources :votings, :monetary_votings, :other_votings, path: :votings, controller: :votings do
    post 'info/:number/at/:position' => 'votings#info_about_number', :as => :number_info_at_position_for
    put 'spend_votes' => 'votings#update_votes_matrix'
    get 'get_timer', as: :timer
    resources :claims, :only => [:create] do
      collection do
        post 'with/:phone' => 'claims#create', constraints: { phone: /\d{10}/ }
      end
    end
    member do
      get 'widget'
      get 'frame'
    end
  end

  scope 'robokassa' do
    match 'paid'    => 'robokassa#paid',    :as => :robokassa_paid # to handle Robokassa push request

    match 'success' => 'robokassa#success', :as => :robokassa_success # to handle Robokassa success redirect
    match 'fail'    => 'robokassa#fail',    :as => :robokassa_fail # to handle Robokassa fail redirect
  end

  match 'auth/:action/callback' => 'omniauth', as: :omniauth
  match 'oauthorize' => 'omniauth#finish_oauthorize'

end

app/models/organization.rb
class Organization < User
  attr_accessible :firstname, :secondname, :fathersname,
                  :org_name, :site, :post_address,
                  :jur_address, :rc, :kc,
                  :bik, :inn, :kpp, :ceo

  #statutory documents
  has_many :documents, dependent: :destroy
  has_many :votings, dependent: :destroy

  validates_format_of :rc, :kc, :bik, :inn, :kpp, with: /[0-9]+/, allow_blank: true
  validates_length_of :inn, minimum: 10, maximum: 12, allow_blank: true
  validates_length_of :rc, is: 20, allow_blank: true
  validates_length_of :kc, is: 20, allow_blank: true
  validates_length_of :bik, is: 9, allow_blank: true
  validates_length_of :kpp, is: 9, allow_blank: true

  def self.need_password? (params)
    params[:email].present? || params[:current_password].present?
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_organization!
  # load_and_authorize_resource

  def show
  end

  def edit
    render :partial => 'form', :locals => { :who => current_organization }
  end

  def drop_document
    drop = current_organization.documents.find(params[:id])
    drop.drop_in_fire unless drop.nil?
    render :json => { :ok => true }
  end

  def drop_voting
    voting = current_organization.votings.find(params[:id])
    voting.destroy unless voting.nil?
    render :json => { :ok => true }
  end
end

app/helpers/organizations_helper.rb
#coding: utf-8
module OrganizationsHelper
  def participants_count
    count = Setting.find('Кол-во участников').value
    count = Participant.count if count.nil?
    count
  end

  def org_count
    count = Setting.find('Кол-во организаций').value
    count = Organization.count if count.nil?
    count
  end

  def voting_count
    count = Setting.find('Кол-во призов').value
    count = Voting.count if count.nil?
    count
  end

end

app/views/organizations/_header.html.haml
-p_c = participants_count
-o_c = org_count
-v_c = voting_count
.org_box_head
  .org_info.org_info_members
    .org_info_number= p_c
    .org_info_text= simple_format( t 'organization.registration.members_info', count: p_c )
  .org_info.org_info_organizators
    .org_info_number= o_c
    .org_info_text= simple_format( t 'organization.registration.organizators_info', count: o_c )
  .org_info.org_info_prizov
    .org_info_number= v_c
    .org_info_text= simple_format( t 'organization.registration.prizov_info', count: v_c )

app/views/organizations/_login.html.haml
#orgreg_page
  .app_div
    %a#orgreg_logo{ :href => '/' }
      %img(src="/images/centr_logo_mini.png")
    .org_box
      = render 'organizations/header'
      .org_box_body
        = form_for @target, 
          url: registration_path('organization'), method: 'post', 
          remote: true, format: :json, 
          html: { id: 'orgreg_logup', class: 'form', name: 'orgreg_logup' } do |f|
          %h1= t 'organization.logup.title'

          %h3= t 'organization.logup.authorization_info'
          .row.three_in_row
            .col= inp f, :email, :between => raw('<span>*</span>')
            .col= inp f, :password, :type => :password_field, :between => raw('<span>*</span>')
            .col= inp f, :password_confirmation, :type => :password_field, :between => raw('<span>*</span>')

          %h3= t 'organization.logup.personal_info'
          .row.two_in_row
            .col= inp f, :secondname, :between => raw('<span>*</span>')
            .col
              = f.label :phone, for: 'phone_mask0'
              %span *
              %input{ id: 'phone_mask0', type: 'text', value: @target.phone }
              = f.hidden_field :phone
              :javascript
                ajok_mask(
                  $('#phone_mask0'),
                  '+7(999)999-99-99',
                  (/^\+7\((\d{3})\)(\d{3})-(\d{2})-(\d{2})$/),
                  '+7(___)___-__-__'
                );
          .row.two_in_row
            .col= inp f, :firstname, :between => raw('<span>*</span>')
            .col= inp f, :fathersname

          %h3= t 'organization.logup.company_info'
          .row.two_in_row
            .col= inp f, :org_name, :between => raw('<span>*</span>')
            .col= inp f, :site

          #orgreg_logup_final_row.row.two_in_row
            #orgreg_logup_notation.col
              %span *
              = t 'organization.logup.field_required'
            .col= f.submit t('organization.logup.submit')

        = form_for @target, 
          url: session_path('organization'), method: 'post', 
          remote: true, format: :json, 
          html: { id: 'orgreg_login', class: 'form', name: 'orgreg_login', 
            data: { login: t('organization.login.errors.wrong'), logout: t('organization.login.errors.logout') } } do |f|
          %h2= t 'organization.login.title'

          #orgreg_login_description= t 'organization.login.description'

          .col= inp f, :login, l_name: 'Email'
          .col
            = link_to t('organization.login.forget'), new_password_path('organization')
            = inp f, :password, :type => :password_field

          .form_error_enter

          = f.submit t 'organization.login.submit'

app/views/organizations/_login.slim
#orgreg_page
  .app_div
    a#orgreg_logo href='/'
      img src="/images/centr_logo_mini.png"
    .org_box
      = render 'organizations/header'
      .org_box_body
        = form_for @target, 
          url: registration_path('organization'), method: 'post', 
          remote: true, format: :json, 
          html: { id: 'orgreg_logup', class: 'form', name: 'orgreg_logup' } do |f|
          h1= t 'organization.logup.title'

          h3= t 'organization.logup.authorization_info'
          .row.three_in_row
            .col= inp f, :email, :between => raw('<span>*</span>')
            .col= inp f, :password, :type => :password_field, :between => raw('<span>*</span>')
            .col= inp f, :password_confirmation, :type => :password_field, :between => raw('<span>*</span>')

          h3= t 'organization.logup.personal_info'
          .row.two_in_row
            .col= inp f, :secondname, :between => raw('<span>*</span>')
            .col
              = f.label :phone, for: 'phone_mask0'
              span *
              input id='phone_mask0' type='text' value=@target.phone
              = f.hidden_field :phone
              javascript:
                ajok_mask(
                  $('#phone_mask0'),
                  '+7(999)999-99-99',
                  (/^\+7\((\d{3})\)(\d{3})-(\d{2})-(\d{2})$/),
                  '+7(___)___-__-__'
                );
          .row.two_in_row
            .col= inp f, :firstname, :between => raw('<span>*</span>')
            .col= inp f, :fathersname

          h3= t 'organization.logup.company_info'
          .row.two_in_row
            .col= inp f, :org_name, :between => raw('<span>*</span>')
            .col= inp f, :site

          .row style='text-align: center; padding-top: 10px;'
              label Условия
              span *
              div
                input type='checkbox' id='terms_agree'
                label for='terms_agree'
                  =link_to 'Я согласен с условиями', '/pages/usloviya', {style: 'line-height:inherit;', target: '_blank'}

          #orgreg_logup_final_row.row.two_in_row
            #orgreg_logup_notation.col
              span *
              = t 'organization.logup.field_required'
            .col= f.submit t('organization.logup.submit')

        javascript:
          $('#orgreg_logup')
          .on('ajax:beforeSend', function(e, xhr, settings){
            var q = $(this);
            if( q.find('#terms_agree').prop('checked') ) return;
            q.trigger('custom:ask', ['Вы согласны с условиями?', q, 'terms_agree']);
            xhr.abort();
            return false;
          })
          .on('terms_agree', function(){
            $(this).find('#terms_agree').prop('checked', true);
            $(this).submit();
            return false;
          });

        = form_for @target, 
          url: session_path('organization'), method: 'post', 
          remote: true, format: :json, 
          html: { id: 'orgreg_login', class: 'form', name: 'orgreg_login', 
            data: { login: t('organization.login.errors.wrong'), logout: t('organization.login.errors.logout') } } do |f|
          h2= t 'organization.login.title'

          #orgreg_login_description= t 'organization.login.description'

          .col= inp f, :login, l_name: 'Email'
          .col
            a id='forget_password' href='#' = t 'organization.login.forget'
            = inp f, :password, :type => :password_field

          .form_error_enter

          = f.submit t 'organization.login.submit'

coffee:
  $ ()->
    smoke = $ '#app_smoke'
    popup = $ '#app_forget'
    both = smoke.add popup

    popup.children('.cross').on 'mousedown', ()->
      both.fadeOut 500
      return false

    $('#forget_password').on 'mousedown', ()->
      both.fadeIn 500
      return false

- content_for :layout_bottom do
  #app_smoke
    #app_log.app_div
      #app_forget.div_in_smoke style='text-align: center'
        .cross &#10006;
        h1 Введите почту организации
        = form_for Organization.new, url: organization_password_path, method: 'post', remote: true, format: :json,
        html: { class: 'form', data: { sended: 'Восстановительное письмо отправлено вам на почту', fail: 'Не удалось отправить письмо. Проверьте правильность почты.' } } do |f|
          = f.text_field :email, style: 'margin: 23px 0px; text-align: center; font-size: 23px;'
          = f.submit 'Восстановить пароль'

app/views/organizations/show.slim
- content_for :top_menu_right do :nothing end
- content_for :layout_bottom do :nothing end

#body.show_votings
  - if current_organization.votings.empty?
    div style='padding: 40px;' 
      = link_to t('organization.cabinet.votings.action.new'), new_voting_path, id: 'organization_show_new_voiting', :class => 'button', style: 'display: block;'

  -else
    h1.tblack
      = t 'organization.cabinet.votings.title'
    table#of_votings border='0' width='100%' cellspacing='0' cellpadding='0'
      tr.twhite.orange.titles
        th.name.first
          p= t 'activerecord.attributes.voting.name'
        th.cost
          p= t 'activerecord.attributes.voting.cost'
        th.budget
          p= t 'activerecord.attributes.voting.budget'
        th.created_at
          p= t 'activerecord.attributes.voting.created_at'
        th.start_date
          p= t 'activerecord.attributes.voting.start_date'
        th.end_date
          p= t 'activerecord.attributes.voting.end_date'
        th.users_population
          p= t 'organization.cabinet.votings.th.users_population'
        th.status
          p= t 'activerecord.attributes.voting.status'
        th.votes_counts
          p
            = t 'organization.cabinet.votings.th.frame'

      - current_organization.votings.each_with_index do |v, i|
        tr class=((i % 2 == 1 ? 'odd lightgrey' : 'even white') + ' tgrey')
          td.first
            div
              .wrapper
                .content
                  = check_box :nothing, "select_#{i}", :class => 'radiocheck', :data => { :target => v.id }
                  = label :nothing, "select_#{i}" do
                    = link_to v.name, edit_voting_path(v)
          td.cost
            p= v.cost
          td
            p= v.budget
          td
            p= l v.created_at.to_date
          td
            p= l v.start_date.to_date
          td
            p= l v.end_date.to_date unless v.end_date.nil?
          td
            p= v.population
          td
            p class="status #{v.status}"
              = t "organization.cabinet.votings.status.#{v.status}"
          td
            p= link_to 'Код', frame_voting_path(v)



    #bottom
      .left= link_to t('organization.cabinet.votings.action.delete'), 'javascript:{}', :class => 'delete action tgreenoblue'
      = link_to t('organization.cabinet.votings.action.new'), new_voting_path, id: 'organization_show_new_voiting', :class => 'button right'